#include "Figure.h"

GLfloat Figure::board[8] = { -3.5f, -2.5f, -1.5f, -0.5f, 0.5f, 1.5f, 2.5f, 3.5f };

std::vector<glm::vec3> Figure::Boards = {
	glm::vec3(Figure::board[0], Figure::board[7], 0.0f), glm::vec3(Figure::board[1], Figure::board[7], 0.0f), glm::vec3(Figure::board[2], Figure::board[7], 0.0f), glm::vec3(Figure::board[3], Figure::board[7], 0.0f), glm::vec3(Figure::board[4], Figure::board[7], 0.0f), glm::vec3(Figure::board[5], Figure::board[7], 0.0f), glm::vec3(Figure::board[6], Figure::board[7], 0.0f), glm::vec3(Figure::board[7], Figure::board[7], 0.0f),
	glm::vec3(Figure::board[0], Figure::board[6], 0.0f), glm::vec3(Figure::board[1], Figure::board[6], 0.0f), glm::vec3(Figure::board[2], Figure::board[6], 0.0f), glm::vec3(Figure::board[3], Figure::board[6], 0.0f), glm::vec3(Figure::board[4], Figure::board[6], 0.0f), glm::vec3(Figure::board[5], Figure::board[6], 0.0f), glm::vec3(Figure::board[6], Figure::board[6], 0.0f), glm::vec3(Figure::board[7], Figure::board[6], 0.0f),
	glm::vec3(Figure::board[0], Figure::board[5], 0.0f), glm::vec3(Figure::board[1], Figure::board[5], 0.0f), glm::vec3(Figure::board[2], Figure::board[5], 0.0f), glm::vec3(Figure::board[3], Figure::board[5], 0.0f), glm::vec3(Figure::board[4], Figure::board[5], 0.0f), glm::vec3(Figure::board[5], Figure::board[5], 0.0f), glm::vec3(Figure::board[6], Figure::board[5], 0.0f), glm::vec3(Figure::board[7], Figure::board[5], 0.0f),
	glm::vec3(Figure::board[0], Figure::board[4], 0.0f), glm::vec3(Figure::board[1], Figure::board[4], 0.0f), glm::vec3(Figure::board[2], Figure::board[4], 0.0f), glm::vec3(Figure::board[3], Figure::board[4], 0.0f), glm::vec3(Figure::board[4], Figure::board[4], 0.0f), glm::vec3(Figure::board[5], Figure::board[4], 0.0f), glm::vec3(Figure::board[6], Figure::board[4], 0.0f), glm::vec3(Figure::board[7], Figure::board[4], 0.0f),
	glm::vec3(Figure::board[0], Figure::board[3], 0.0f), glm::vec3(Figure::board[1], Figure::board[3], 0.0f), glm::vec3(Figure::board[2], Figure::board[3], 0.0f), glm::vec3(Figure::board[3], Figure::board[3], 0.0f), glm::vec3(Figure::board[4], Figure::board[3], 0.0f), glm::vec3(Figure::board[5], Figure::board[3], 0.0f), glm::vec3(Figure::board[6], Figure::board[3], 0.0f), glm::vec3(Figure::board[7], Figure::board[3], 0.0f),
	glm::vec3(Figure::board[0], Figure::board[2], 0.0f), glm::vec3(Figure::board[1], Figure::board[2], 0.0f), glm::vec3(Figure::board[2], Figure::board[2], 0.0f), glm::vec3(Figure::board[3], Figure::board[2], 0.0f), glm::vec3(Figure::board[4], Figure::board[2], 0.0f), glm::vec3(Figure::board[5], Figure::board[2], 0.0f), glm::vec3(Figure::board[6], Figure::board[2], 0.0f), glm::vec3(Figure::board[7], Figure::board[2], 0.0f),
	glm::vec3(Figure::board[0], Figure::board[1], 0.0f), glm::vec3(Figure::board[1], Figure::board[1], 0.0f), glm::vec3(Figure::board[2], Figure::board[1], 0.0f), glm::vec3(Figure::board[3], Figure::board[1], 0.0f), glm::vec3(Figure::board[4], Figure::board[1], 0.0f), glm::vec3(Figure::board[5], Figure::board[1], 0.0f), glm::vec3(Figure::board[6], Figure::board[1], 0.0f), glm::vec3(Figure::board[7], Figure::board[1], 0.0f),
	glm::vec3(Figure::board[0], Figure::board[0], 0.0f), glm::vec3(Figure::board[1], Figure::board[0], 0.0f), glm::vec3(Figure::board[2], Figure::board[0], 0.0f), glm::vec3(Figure::board[3], Figure::board[0], 0.0f), glm::vec3(Figure::board[4], Figure::board[0], 0.0f), glm::vec3(Figure::board[5], Figure::board[0], 0.0f), glm::vec3(Figure::board[6], Figure::board[0], 0.0f), glm::vec3(Figure::board[7], Figure::board[0], 0.0f),
};
